### ISSUE TITLE
Deis router fails to start on minikube

### ISSUE THREAD

**Issue by TheKangaroo** [deis/router#217] opened 2016-07-14 18:57 UTC
i'm about to set up a test environment for deis with the new k8s minikube. 
(http://kubernetes.io/docs/getting-started-guides/minikube/)

But deis-router fails to start since port 9090 is already  in use by minikube

`kd describe pods deis-router-v57v6
3m	3m	1	{kubelet minikubevm}		Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: Error response from daemon: driver failed programming external connectivity on endpoint k8s_POD.17406e7a_deis-router-v57v6_deis_a795820e-49f0-11e6-9b7b-da1a2de3d2a0_95bffcd5 (03aa1b5634499ac9889e9e1673997aa42a0973852d918e4d8f49bdc27880a2f4): Error starting userland proxy: listen tcp 0.0.0.0:9090: bind: address already in use"`

`minikube ssh
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.11.1, build master : 901340f - Fri Jul  1 22:52:19 UTC 2016
Docker version 1.11.1, build 5604cbe
docker@minikubeVM:~$ sudo netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2397/sshd
tcp        0      0 127.0.0.1:9090          0.0.0.0:*               LISTEN      2848/localkube
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      2848/localkube
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      2848/localkube
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      2848/localkube
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      2848/localkube
tcp        0      0 10.0.2.15:53            0.0.0.0:*               LISTEN      2848/localkube
tcp        0      0 :::22                   :::*                    LISTEN      2397/sshd
tcp        0      0 :::8443                 :::*                    LISTEN      2848/localkube
tcp        0      0 :::30620                :::*                    LISTEN      2848/localkube
tcp        0      0 :::4194                 :::*                    LISTEN      2848/localkube
tcp        0      0 :::31557                :::*                    LISTEN      2848/localkube
tcp        0      0 :::31654                :::*                    LISTEN      2848/localkube
tcp        0      0 :::2376                 :::*                    LISTEN      2711/docker
tcp        0      0 :::10250                :::*                    LISTEN      2848/localkube
tcp        0      0 :::10251                :::*                    LISTEN      2848/localkube
tcp        0      0 :::10252                :::*                    LISTEN      2848/localkube
tcp        0      0 :::10255                :::*                    LISTEN      2848/localkube
tcp        0      0 :::30000                :::*                    LISTEN      2848/localkube
tcp        0      0 :::8081                 :::*                    LISTEN      2848/localkube
tcp        0      0 :::31923                :::*                    LISTEN      2848/localkube
udp        0      0 10.0.2.15:53            0.0.0.0:*                           2848/localkube`

i'm not sure how to avoid this.
Any ideas how to work around this issue?
Thanks in advance

**Comment by bacongobbler** [comment] 2016-07-14 19:11
Closing this as a duplicate of https://github.com/deis/router/issues/188#issuecomment-219567418. The best way to work around this would be to remove the `hostPort` entries in the router chart manifest. :)

**Closed by bacongobbler** 2016-07-14 19:11 UTC
