### ISSUE TITLE
Proposal: add debug server 

### ISSUE THREAD

**Issue by aledbf** [deis/router#2] opened 2015-11-25 16:05 UTC
This post [capturing-5xx-errors-debug-server](https://www.nginx.com/blog/capturing-5xx-errors-debug-server) shows how is possible to use a custom upstream to forward errors and obtain more details about the reason. This also enables the customization of the default and error pages (https://github.com/deis/deis/issues/1082) without the need of a custom image

**Comment by krancour** [comment] 2016-02-12 17:52
I think this is an interesting idea, for sure, but I'm thinking about how this could be implemented, and the scope seems quite large.  My thinking on the matter follows...

Per the referenced article, doing this requires additional "application servers" that are configured differently-- with debug logging and other instrumentation cranked all the way up.  In the k8s world, that means one or more differently configured _pods_.  A replication controller can't juggle heterogeneously configured pods.  That is to say, a single replication controller cannot manage pods with two different templates-- one for the pods optimized for performance and another for the pod(s) optimized for debugging.  This being the case, it means we'd need to introduce a _second_ RC.

How can that be done?  I see two options.  Option one, workflow evolves to juggle two RCs, two services, and two separate sets of configuration for any app that has opted into this.  Effort-wise, that seems nothing short of daunting.  The second option would be that users who want this sort of setup for an app actually deploy a _second_ app from the same codebase, but with different configuration.  That much can already be done today, _but_ workflow would still have to be modified quite significantly to model the relationship between the two applications so that it can, in turn, somehow inform the router that one of the two apps is a normal, routable app, and that the other is the special one where requests resulting in 5xxs fail over to.  What's worse is that we'd have to figure out how to coordinate deployments across the two applications, or else there's no guarantee that the debug pods are running the same build as the others.

My gut says that capturing and reporting on errors is more appropriately and more easily handled in the application space.  Using the likes of Airbrake or Errbit strikes me as a better starting point for implementing such functionality than by making the platform responsible for failover to "debug servers."

**Comment by helgi** [comment] 2016-02-12 18:59
This is a neat idea but @krancour also touched on all the complexity it will bring into workflow.

Another thing to realise is that we may not stick with Nginx for the router, it may turn into HAProxy or any N alternative solutions that a customer can come up with. Tightly coupling the debug functionality from router to workflow to application would make that a lil bit cumbersome.

That being said, I think this is interesting and could be achieved via `PetSet` when that comes out in k8s without a massive amount of workflow work but a few things may have to line up on k8s and other projects for it to be viable.

Other option I would be curious in looking into is how the new logger and related projects in Deis (/cc @jchauncey) can help with this without requiring a debug server, that's mostly just nginx showing off how you can make such introspection happen using their product ;)

**Comment by jchauncey** [comment] 2016-02-12 19:51
If we logged all of the errors to an errors file we could stream that from fluentd to whereever we wanted.

**Comment by krancour** [comment] 2016-02-12 21:03
@jchauncey why bother with a file?  Containerized processes should log to stdout / stderr, and if deis-logger is installed, fluentd's already getting all that stuff.  Maybe can we just document the tweaks one must make to the fluentd daemonset to stream logs to some additional endoint for archive or analysis?  e.g. Papertrail or Splunk, etc.?

On a sidenote, what is really neat about what @aledbf has proposed is that you get a more _detailed_ trace when something goes wrong because failed requests fail over to an app server that has debug logging and instrumentation cranked all the way up.  This would expose a lot of information about the root cause of a problem that wouldn't be available via the alternatives we've proposed (Airbrake, Errbit, PetSet, log stream processing).

That being said, I still think the massive amount of work required to implement this as a platform feature is disproportionate to the demand for it-- neat though this proposal is, this isn't really common way of doing things.  I'm going to close this out for now.

**Closed by krancour** 2016-02-12 21:03 UTC
