### ISSUE TITLE
hostname doesn't resolve for 3 mins

### ISSUE THREAD

**Issue by helgi** [deis/router#83] opened 2016-01-13 01:39 UTC
Did a `git push` for workflow and then tried to hit the app when it said it worked.

Couldn't for full 3 minutes

```
To ssh://git@deis.10.3.0.161.xip.io:2222/madcap-ricochet.git
   • [new branch]      master -> master
     core@micro-kube ~/example-go $ curl madcap-ricochet.10.3.0.161.xip.io
     curl: (6) Couldn't resolve host 'madcap-ricochet.10.3.0.161.xip.io'
     core@micro-kube ~/example-go $ curl madcap-ricochet.10.3.0.161.xip.io
     curl: (6) Couldn't resolve host 'madcap-ricochet.10.3.0.161.xip.io'
     core@micro-kube ~/example-go $ curl madcap-ricochet.10.3.0.161.xip.io
     curl: (6) Couldn't resolve host 'madcap-ricochet.10.3.0.161.xip.io'
     core@micro-kube ~/example-go $ curl madcap-ricochet.10.3.0.161.xip.io
     curl: (6) Couldn't resolve host 'madcap-ricochet.10.3.0.161.xip.io'
     core@micro-kube ~/example-go $ curl madcap-ricochet.10.3.0.161.xip.io
     Powered by Deis
     Release v2 on madcap-ricochet-v2-web-d771p
```

However looking at the router logs you can see it reloaded on time (confirmed the timings)

```
2016/01/13 01:25:09 INFO: Router configuration has changed in k8s.
2016/01/13 01:25:09 INFO: Reloading nginx...
2016/01/13 01:25:09 INFO: nginx reloaded.
2016/01/13 01:25:09 [notice] 12#0: signal process started
[13/Jan/2016:01:27:53 +0000] - 10.2.22.1 - - - 200 - "GET / HTTP/1.1" - 221 - "-" - "curl/7.43.0" - "~^madcap-ricochet\x5C.(?<domain>.+)$" - 10.3.0.37:80 - madcap-ricochet.10.3.0.161.xip.io - 0.001 - 0.001
```

**Comment by arschles** [comment] 2016-01-13 15:18
Just to make sure, is a slugrunner pod (in the madcap-ricochet namespace) up and running?

**Comment by krancour** [comment] 2016-01-13 16:02
@arschles asks a good question.  The trace above looks unusual.  Usually after I push, I have to wait some time while slugbuilder is pulled down to whatever node will be doing the build (if the image isn't already there) and then some more while slugrunner is pulled down to the node that will be running the app (again, if the image isn't already there), and then there's some lesser time required for the slug itself to be pulled down.  I wouldn't usually try to hit the app until the build's trace shows it's complete, but I don't see that in the trace you posted.

**Comment by krancour** [comment] 2016-01-18 21:03
@helgi do we have any more information about this?  This looks like it was probably a delay in container pull or startup.

**Comment by helgi** [comment] 2016-01-18 22:07
No more info than the above. No real logs anywhere to be found that indicated anything specifically went wrong, at least logs I looked at.

**Comment by krancour** [comment] 2016-01-20 17:59
I haven't been able to reproduce this.  I'm closing it, but please re-open if it recurs.

**Closed by krancour** 2016-01-20 17:59 UTC
