### ISSUE TITLE
Router pod hanges in Pending state indefinitely

### ISSUE THREAD

**Issue by olalonde** [deis/router#95] opened 2016-01-20 07:56 UTC
I was attempting to install deis v2-alpha for the first time on a local vagrant [coreos-kubernetes](https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant-single.html) single node and the router pod seems to hang in "Pending" state indefinitely.

```bash
~/code/deis$ helm -v
helm version 0.3.1+d4c0fa8
~/code/deis$ kubectl version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.7", GitCommit:"6234d6a0abd3323cd08c52602e4a91e47fc9491c", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.7", GitCommit:"6234d6a0abd3323cd08c52602e4a91e47fc9491c", GitTreeState:"clean"}
~/code/deis$ kubectl get events
FIRSTSEEN   LASTSEEN   COUNT     NAME      KIND      SUBOBJECT   REASON    SOURCE    MESSAGE
~/code/deis$ kubectl get events --namespace=deis
FIRSTSEEN                         LASTSEEN                          COUNT     NAME                        KIND                    SUBOBJECT                              REASON             SOURCE                      MESSAGE
Tue, 19 Jan 2016 23:35:47 -0800   Tue, 19 Jan 2016 23:35:47 -0800   1         deis-builder-vc0xg          Pod                     implicitly required container POD      started            {kubelet 172.17.4.99}       Started with docker id 2c17701859c0
Tue, 19 Jan 2016 23:35:47 -0800   Tue, 19 Jan 2016 23:35:47 -0800   1         deis-etcd-discovery         ReplicationController                                          successfulCreate   {replication-controller }   Created pod: deis-etcd-discovery-unf2g
Tue, 19 Jan 2016 23:35:47 -0800   Tue, 19 Jan 2016 23:35:47 -0800   1         deis-builder                ReplicationController                                          successfulCreate   {replication-controller }   Created pod: deis-builder-vc0xg
Tue, 19 Jan 2016 23:35:47 -0800   Tue, 19 Jan 2016 23:35:47 -0800   1         deis-database-3rwhk         Pod                                                            scheduled          {scheduler }                Successfully assigned deis-database-3rwhk to 172.17.4.99
Tue, 19 Jan 2016 23:35:47 -0800   Tue, 19 Jan 2016 23:35:47 -0800   1         deis-database-3rwhk         Pod                     implicitly required container POD      pulled             {kubelet 172.17.4.99}       Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
Tue, 19 Jan 2016 23:35:47 -0800   Tue, 19 Jan 2016 23:35:47 -0800   1         deis-database-3rwhk         Pod                     implicitly required container POD      created            {kubelet 172.17.4.99}       Created with docker id 072caafe0524
Tue, 19 Jan 2016 23:35:47 -0800   Tue, 19 Jan 2016 23:35:47 -0800   1         deis-database-3rwhk         Pod                     implicitly required container POD      started            {kubelet 172.17.4.99}       Started with docker id 072caafe0524
Tue, 19 Jan 2016 23:35:47 -0800   Tue, 19 Jan 2016 23:35:47 -0800   1         deis-builder-vc0xg          Pod                                                            scheduled          {scheduler }                Successfully assigned deis-builder-vc0xg to 172.17.4.99
Tue, 19 Jan 2016 23:35:47 -0800   Tue, 19 Jan 2016 23:35:47 -0800   1         deis-builder-vc0xg          Pod                     implicitly required container POD      pulled             {kubelet 172.17.4.99}       Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
Tue, 19 Jan 2016 23:35:47 -0800   Tue, 19 Jan 2016 23:35:47 -0800   1         deis-database               ReplicationController                                          successfulCreate   {replication-controller }   Created pod: deis-database-3rwhk
Tue, 19 Jan 2016 23:35:47 -0800   Tue, 19 Jan 2016 23:35:47 -0800   1         deis-etcd-discovery-unf2g   Pod                                                            scheduled          {scheduler }                Successfully assigned deis-etcd-discovery-unf2g to 172.17.4.99
Tue, 19 Jan 2016 23:35:47 -0800   Tue, 19 Jan 2016 23:35:47 -0800   1         deis-builder-vc0xg          Pod                     implicitly required container POD      created            {kubelet 172.17.4.99}       Created with docker id 2c17701859c0
Tue, 19 Jan 2016 23:35:48 -0800   Tue, 19 Jan 2016 23:35:48 -0800   1         deis-etcd-1                 ReplicationController                                          successfulCreate   {replication-controller }   Created pod: deis-etcd-1-7asrh
Tue, 19 Jan 2016 23:35:48 -0800   Tue, 19 Jan 2016 23:35:48 -0800   1         deis-etcd-discovery-unf2g   Pod                     implicitly required container POD      started            {kubelet 172.17.4.99}       Started with docker id e67f1295ba7f
Tue, 19 Jan 2016 23:35:48 -0800   Tue, 19 Jan 2016 23:35:48 -0800   1         deis-etcd-1-7asrh           Pod                                                            scheduled          {scheduler }                Successfully assigned deis-etcd-1-7asrh to 172.17.4.99
Tue, 19 Jan 2016 23:35:48 -0800   Tue, 19 Jan 2016 23:35:48 -0800   1         deis-etcd-discovery-unf2g   Pod                     implicitly required container POD      created            {kubelet 172.17.4.99}       Created with docker id e67f1295ba7f
Tue, 19 Jan 2016 23:35:48 -0800   Tue, 19 Jan 2016 23:35:48 -0800   1         deis-etcd-1-33zlc           Pod                                                            scheduled          {scheduler }                Successfully assigned deis-etcd-1-33zlc to 172.17.4.99
Tue, 19 Jan 2016 23:35:48 -0800   Tue, 19 Jan 2016 23:35:48 -0800   1         deis-etcd-discovery-unf2g   Pod                     implicitly required container POD      pulled             {kubelet 172.17.4.99}       Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
Tue, 19 Jan 2016 23:35:48 -0800   Tue, 19 Jan 2016 23:35:48 -0800   1         deis-etcd-1                 ReplicationController                                          successfulCreate   {replication-controller }   Created pod: deis-etcd-1-33zlc
Tue, 19 Jan 2016 23:35:48 -0800   Tue, 19 Jan 2016 23:35:48 -0800   1         deis-etcd-1                 ReplicationController                                          successfulCreate   {replication-controller }   Created pod: deis-etcd-1-a8d98
Tue, 19 Jan 2016 23:35:48 -0800   Tue, 19 Jan 2016 23:35:48 -0800   1         deis-etcd-1-a8d98           Pod                                                            scheduled          {scheduler }                Successfully assigned deis-etcd-1-a8d98 to 172.17.4.99
Tue, 19 Jan 2016 23:35:49 -0800   Tue, 19 Jan 2016 23:35:49 -0800   1         deis-etcd-1-7asrh           Pod                     implicitly required container POD      created            {kubelet 172.17.4.99}       Created with docker id e8a7282684c9
Tue, 19 Jan 2016 23:35:49 -0800   Tue, 19 Jan 2016 23:35:49 -0800   1         deis-minio-35irj            Pod                                                            scheduled          {scheduler }                Successfully assigned deis-minio-35irj to 172.17.4.99
Tue, 19 Jan 2016 23:35:49 -0800   Tue, 19 Jan 2016 23:35:49 -0800   1         deis-registry               ReplicationController                                          successfulCreate   {replication-controller }   Created pod: deis-registry-x40ur
Tue, 19 Jan 2016 23:35:49 -0800   Tue, 19 Jan 2016 23:35:49 -0800   1         deis-minio                  ReplicationController                                          successfulCreate   {replication-controller }   Created pod: deis-minio-35irj
Tue, 19 Jan 2016 23:35:49 -0800   Tue, 19 Jan 2016 23:35:49 -0800   1         deis-etcd-1-7asrh           Pod                     implicitly required container POD      pulled             {kubelet 172.17.4.99}       Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
Tue, 19 Jan 2016 23:35:49 -0800   Tue, 19 Jan 2016 23:35:49 -0800   1         deis-router                 ReplicationController                                          successfulCreate   {replication-controller }   Created pod: deis-router-3pgpt
Tue, 19 Jan 2016 23:35:49 -0800   Tue, 19 Jan 2016 23:35:49 -0800   1         deis-etcd-1-33zlc           Pod                     implicitly required container POD      pulled             {kubelet 172.17.4.99}       Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
Tue, 19 Jan 2016 23:35:49 -0800   Tue, 19 Jan 2016 23:35:49 -0800   1         deis-etcd-1-33zlc           Pod                     implicitly required container POD      created            {kubelet 172.17.4.99}       Created with docker id 8d56e3becc0d
Tue, 19 Jan 2016 23:35:49 -0800   Tue, 19 Jan 2016 23:35:49 -0800   1         deis-etcd-1-33zlc           Pod                     implicitly required container POD      started            {kubelet 172.17.4.99}       Started with docker id 8d56e3becc0d
Tue, 19 Jan 2016 23:35:49 -0800   Tue, 19 Jan 2016 23:35:49 -0800   1         deis-registry-x40ur         Pod                                                            scheduled          {scheduler }                Successfully assigned deis-registry-x40ur to 172.17.4.99
Tue, 19 Jan 2016 23:35:50 -0800   Tue, 19 Jan 2016 23:35:50 -0800   1         deis-registry-x40ur         Pod                     implicitly required container POD      started            {kubelet 172.17.4.99}       Started with docker id 62e3c011dc90
Tue, 19 Jan 2016 23:35:50 -0800   Tue, 19 Jan 2016 23:35:50 -0800   1         deis-workflow-ojpi2         Pod                                                            scheduled          {scheduler }                Successfully assigned deis-workflow-ojpi2 to 172.17.4.99
Tue, 19 Jan 2016 23:35:50 -0800   Tue, 19 Jan 2016 23:35:50 -0800   1         deis-registry-x40ur         Pod                     implicitly required container POD      created            {kubelet 172.17.4.99}       Created with docker id 62e3c011dc90
Tue, 19 Jan 2016 23:35:50 -0800   Tue, 19 Jan 2016 23:35:50 -0800   1         deis-etcd-1-7asrh           Pod                     implicitly required container POD      started            {kubelet 172.17.4.99}       Started with docker id e8a7282684c9
Tue, 19 Jan 2016 23:35:50 -0800   Tue, 19 Jan 2016 23:35:50 -0800   1         deis-registry-x40ur         Pod                     implicitly required container POD      pulled             {kubelet 172.17.4.99}       Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
Tue, 19 Jan 2016 23:35:50 -0800   Tue, 19 Jan 2016 23:35:50 -0800   1         deis-etcd-1-a8d98           Pod                     implicitly required container POD      pulled             {kubelet 172.17.4.99}       Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
Tue, 19 Jan 2016 23:35:50 -0800   Tue, 19 Jan 2016 23:35:50 -0800   1         deis-etcd-1-a8d98           Pod                     implicitly required container POD      created            {kubelet 172.17.4.99}       Created with docker id 016dad3a94c3
Tue, 19 Jan 2016 23:35:50 -0800   Tue, 19 Jan 2016 23:35:50 -0800   1         deis-etcd-1-a8d98           Pod                     implicitly required container POD      started            {kubelet 172.17.4.99}       Started with docker id 016dad3a94c3
Tue, 19 Jan 2016 23:35:50 -0800   Tue, 19 Jan 2016 23:35:50 -0800   1         deis-workflow               ReplicationController                                          successfulCreate   {replication-controller }   Created pod: deis-workflow-ojpi2
Tue, 19 Jan 2016 23:35:51 -0800   Tue, 19 Jan 2016 23:35:51 -0800   2         deis-etcd-1-7asrh           Pod                     spec.containers{deis-etcd-1}           failed             {kubelet 172.17.4.99}       Failed to create docker container with error: no such image
Tue, 19 Jan 2016 23:35:52 -0800   Tue, 19 Jan 2016 23:35:52 -0800   1         deis-minio-35irj            Pod                     implicitly required container POD      started            {kubelet 172.17.4.99}       Started with docker id 6d55db862512
Tue, 19 Jan 2016 23:35:52 -0800   Tue, 19 Jan 2016 23:35:52 -0800   1         deis-minio-35irj            Pod                     implicitly required container POD      created            {kubelet 172.17.4.99}       Created with docker id 6d55db862512
Tue, 19 Jan 2016 23:35:52 -0800   Tue, 19 Jan 2016 23:35:52 -0800   1         deis-workflow-ojpi2         Pod                     implicitly required container POD      pulled             {kubelet 172.17.4.99}       Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
Tue, 19 Jan 2016 23:35:52 -0800   Tue, 19 Jan 2016 23:35:52 -0800   1         deis-workflow-ojpi2         Pod                     implicitly required container POD      started            {kubelet 172.17.4.99}       Started with docker id e11edbcf8edb
Tue, 19 Jan 2016 23:35:52 -0800   Tue, 19 Jan 2016 23:35:52 -0800   1         deis-workflow-ojpi2         Pod                     implicitly required container POD      created            {kubelet 172.17.4.99}       Created with docker id e11edbcf8edb
Tue, 19 Jan 2016 23:35:52 -0800   Tue, 19 Jan 2016 23:35:52 -0800   1         deis-minio-35irj            Pod                     implicitly required container POD      pulled             {kubelet 172.17.4.99}       Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
Tue, 19 Jan 2016 23:36:58 -0800   Tue, 19 Jan 2016 23:36:58 -0800   1         deis-etcd-1-7asrh           Pod                     spec.containers{deis-etcd-1}           started            {kubelet 172.17.4.99}       Started with docker id 71d22054cf12
Tue, 19 Jan 2016 23:36:58 -0800   Tue, 19 Jan 2016 23:36:58 -0800   1         deis-etcd-1-33zlc           Pod                     spec.containers{deis-etcd-1}           created            {kubelet 172.17.4.99}       Created with docker id b35e0b0e83cf
Tue, 19 Jan 2016 23:36:58 -0800   Tue, 19 Jan 2016 23:36:58 -0800   1         deis-etcd-1-33zlc           Pod                     spec.containers{deis-etcd-1}           pulled             {kubelet 172.17.4.99}       Successfully pulled image "quay.io/deis/etcd:2.0.0-alpha"
Tue, 19 Jan 2016 23:36:58 -0800   Tue, 19 Jan 2016 23:36:58 -0800   1         deis-etcd-1-a8d98           Pod                     spec.containers{deis-etcd-1}           pulled             {kubelet 172.17.4.99}       Successfully pulled image "quay.io/deis/etcd:2.0.0-alpha"
Tue, 19 Jan 2016 23:36:58 -0800   Tue, 19 Jan 2016 23:36:58 -0800   1         deis-etcd-1-a8d98           Pod                     spec.containers{deis-etcd-1}           created            {kubelet 172.17.4.99}       Created with docker id 8efd01257eaa
Tue, 19 Jan 2016 23:36:58 -0800   Tue, 19 Jan 2016 23:36:58 -0800   1         deis-etcd-1-7asrh           Pod                     spec.containers{deis-etcd-1}           created            {kubelet 172.17.4.99}       Created with docker id 71d22054cf12
Tue, 19 Jan 2016 23:36:58 -0800   Tue, 19 Jan 2016 23:36:58 -0800   1         deis-etcd-discovery-unf2g   Pod                     spec.containers{deis-etcd-discovery}   created            {kubelet 172.17.4.99}       Created with docker id 92dca6015865
Tue, 19 Jan 2016 23:36:58 -0800   Tue, 19 Jan 2016 23:36:58 -0800   1         deis-etcd-discovery-unf2g   Pod                     spec.containers{deis-etcd-discovery}   pulled             {kubelet 172.17.4.99}       Successfully pulled image "quay.io/deis/etcd:2.0.0-alpha"
Tue, 19 Jan 2016 23:35:51 -0800   Tue, 19 Jan 2016 23:36:58 -0800   3         deis-etcd-1-7asrh           Pod                     spec.containers{deis-etcd-1}           pulled             {kubelet 172.17.4.99}       Successfully pulled image "quay.io/deis/etcd:2.0.0-alpha"
Tue, 19 Jan 2016 23:36:59 -0800   Tue, 19 Jan 2016 23:36:59 -0800   1         deis-etcd-discovery-unf2g   Pod                     spec.containers{deis-etcd-discovery}   started            {kubelet 172.17.4.99}       Started with docker id 92dca6015865
Tue, 19 Jan 2016 23:36:59 -0800   Tue, 19 Jan 2016 23:36:59 -0800   1         deis-etcd-1-a8d98           Pod                     spec.containers{deis-etcd-1}           started            {kubelet 172.17.4.99}       Started with docker id 8efd01257eaa
Tue, 19 Jan 2016 23:36:59 -0800   Tue, 19 Jan 2016 23:36:59 -0800   1         deis-etcd-1-33zlc           Pod                     spec.containers{deis-etcd-1}           started            {kubelet 172.17.4.99}       Started with docker id b35e0b0e83cf
Tue, 19 Jan 2016 23:36:59 -0800   Tue, 19 Jan 2016 23:36:59 -0800   1         deis-etcd-1-7asrh           Pod                     spec.containers{deis-etcd-1}           created            {kubelet 172.17.4.99}       Created with docker id 25c8e7a8026b
Tue, 19 Jan 2016 23:36:59 -0800   Tue, 19 Jan 2016 23:36:59 -0800   1         deis-etcd-1-7asrh           Pod                     spec.containers{deis-etcd-1}           started            {kubelet 172.17.4.99}       Started with docker id 25c8e7a8026b
Tue, 19 Jan 2016 23:37:00 -0800   Tue, 19 Jan 2016 23:37:00 -0800   1         deis-etcd-1-7asrh           Pod                     spec.containers{deis-etcd-1}           started            {kubelet 172.17.4.99}       Started with docker id 55077cb60778
Tue, 19 Jan 2016 23:37:00 -0800   Tue, 19 Jan 2016 23:37:00 -0800   1         deis-etcd-1-33zlc           Pod                     spec.containers{deis-etcd-1}           created            {kubelet 172.17.4.99}       Created with docker id 1b2c4809d343
Tue, 19 Jan 2016 23:37:00 -0800   Tue, 19 Jan 2016 23:37:00 -0800   1         deis-etcd-1-7asrh           Pod                     spec.containers{deis-etcd-1}           created            {kubelet 172.17.4.99}       Created with docker id 55077cb60778
Tue, 19 Jan 2016 23:37:00 -0800   Tue, 19 Jan 2016 23:37:00 -0800   1         deis-etcd-1-a8d98           Pod                     spec.containers{deis-etcd-1}           started            {kubelet 172.17.4.99}       Started with docker id c5942ad1fb6d
Tue, 19 Jan 2016 23:37:00 -0800   Tue, 19 Jan 2016 23:37:00 -0800   1         deis-etcd-1-a8d98           Pod                     spec.containers{deis-etcd-1}           created            {kubelet 172.17.4.99}       Created with docker id c5942ad1fb6d
Tue, 19 Jan 2016 23:37:01 -0800   Tue, 19 Jan 2016 23:37:01 -0800   1         deis-etcd-1-33zlc           Pod                     spec.containers{deis-etcd-1}           started            {kubelet 172.17.4.99}       Started with docker id 1b2c4809d343
Tue, 19 Jan 2016 23:37:10 -0800   Tue, 19 Jan 2016 23:37:10 -0800   1         deis-etcd-1-33zlc           Pod                     spec.containers{deis-etcd-1}           started            {kubelet 172.17.4.99}       Started with docker id 52e43cf0db66
Tue, 19 Jan 2016 23:37:10 -0800   Tue, 19 Jan 2016 23:37:10 -0800   1         deis-etcd-1-33zlc           Pod                     spec.containers{deis-etcd-1}           created            {kubelet 172.17.4.99}       Created with docker id 52e43cf0db66
Tue, 19 Jan 2016 23:37:10 -0800   Tue, 19 Jan 2016 23:37:10 -0800   1         deis-etcd-1-7asrh           Pod                     spec.containers{deis-etcd-1}           created            {kubelet 172.17.4.99}       Created with docker id 739a5a27bfeb
Tue, 19 Jan 2016 23:37:10 -0800   Tue, 19 Jan 2016 23:37:10 -0800   1         deis-etcd-1-a8d98           Pod                     spec.containers{deis-etcd-1}           created            {kubelet 172.17.4.99}       Created with docker id 061026e257b5
Tue, 19 Jan 2016 23:37:11 -0800   Tue, 19 Jan 2016 23:37:11 -0800   1         deis-etcd-1-a8d98           Pod                     spec.containers{deis-etcd-1}           started            {kubelet 172.17.4.99}       Started with docker id 061026e257b5
Tue, 19 Jan 2016 23:37:11 -0800   Tue, 19 Jan 2016 23:37:11 -0800   1         deis-etcd-1-7asrh           Pod                     spec.containers{deis-etcd-1}           started            {kubelet 172.17.4.99}       Started with docker id 739a5a27bfeb
Tue, 19 Jan 2016 23:38:01 -0800   Tue, 19 Jan 2016 23:38:01 -0800   1         deis-registry-x40ur         Pod                     spec.containers{deis-registry}         created            {kubelet 172.17.4.99}       Created with docker id b567282af91f
Tue, 19 Jan 2016 23:38:01 -0800   Tue, 19 Jan 2016 23:38:01 -0800   1         deis-registry-x40ur         Pod                     spec.containers{deis-registry}         started            {kubelet 172.17.4.99}       Started with docker id b567282af91f
Tue, 19 Jan 2016 23:38:01 -0800   Tue, 19 Jan 2016 23:38:01 -0800   1         deis-registry-x40ur         Pod                     spec.containers{deis-registry}         pulled             {kubelet 172.17.4.99}       Successfully pulled image "quay.io/deis/registry:2.0.0-alpha"
Tue, 19 Jan 2016 23:39:20 -0800   Tue, 19 Jan 2016 23:39:20 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         pulled             {kubelet 172.17.4.99}       Successfully pulled image "quay.io/deis/workflow:2.0.0-alpha"
Tue, 19 Jan 2016 23:39:20 -0800   Tue, 19 Jan 2016 23:39:20 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         created            {kubelet 172.17.4.99}       Created with docker id aba00a6696a1
Tue, 19 Jan 2016 23:39:20 -0800   Tue, 19 Jan 2016 23:39:20 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         started            {kubelet 172.17.4.99}       Started with docker id aba00a6696a1
Tue, 19 Jan 2016 23:39:52 -0800   Tue, 19 Jan 2016 23:39:52 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         created            {kubelet 172.17.4.99}       Created with docker id 920004ef72a9
Tue, 19 Jan 2016 23:39:52 -0800   Tue, 19 Jan 2016 23:39:52 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         started            {kubelet 172.17.4.99}       Started with docker id 920004ef72a9
Tue, 19 Jan 2016 23:40:21 -0800   Tue, 19 Jan 2016 23:40:21 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         created            {kubelet 172.17.4.99}       Created with docker id 9a1e0f032687
Tue, 19 Jan 2016 23:40:21 -0800   Tue, 19 Jan 2016 23:40:21 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         started            {kubelet 172.17.4.99}       Started with docker id 9a1e0f032687
Tue, 19 Jan 2016 23:40:40 -0800   Tue, 19 Jan 2016 23:40:40 -0800   1         deis-builder-vc0xg          Pod                     spec.containers{deis-builder}          pulled             {kubelet 172.17.4.99}       Successfully pulled image "quay.io/deis/builder:2.0.0-alpha"
Tue, 19 Jan 2016 23:40:41 -0800   Tue, 19 Jan 2016 23:40:41 -0800   1         deis-builder-vc0xg          Pod                     spec.containers{deis-builder}          created            {kubelet 172.17.4.99}       Created with docker id 0e9770e7b592
Tue, 19 Jan 2016 23:40:41 -0800   Tue, 19 Jan 2016 23:40:41 -0800   1         deis-builder-vc0xg          Pod                     spec.containers{deis-builder}          started            {kubelet 172.17.4.99}       Started with docker id 0e9770e7b592
Tue, 19 Jan 2016 23:40:51 -0800   Tue, 19 Jan 2016 23:40:51 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         started            {kubelet 172.17.4.99}       Started with docker id 2cd7e24b4baf
Tue, 19 Jan 2016 23:40:51 -0800   Tue, 19 Jan 2016 23:40:51 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         created            {kubelet 172.17.4.99}       Created with docker id 2cd7e24b4baf
Tue, 19 Jan 2016 23:41:03 -0800   Tue, 19 Jan 2016 23:41:03 -0800   1         deis-minio-35irj            Pod                     spec.containers{deis-minio}            created            {kubelet 172.17.4.99}       Created with docker id 2783dd751d72
Tue, 19 Jan 2016 23:41:03 -0800   Tue, 19 Jan 2016 23:41:03 -0800   1         deis-minio-35irj            Pod                     spec.containers{deis-minio}            started            {kubelet 172.17.4.99}       Started with docker id 2783dd751d72
Tue, 19 Jan 2016 23:41:03 -0800   Tue, 19 Jan 2016 23:41:03 -0800   1         deis-minio-35irj            Pod                     spec.containers{deis-minio}            pulled             {kubelet 172.17.4.99}       Successfully pulled image "quay.io/deis/minio:2.0.0-alpha"
Tue, 19 Jan 2016 23:41:21 -0800   Tue, 19 Jan 2016 23:41:21 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         started            {kubelet 172.17.4.99}       Started with docker id 922bebaa64fa
Tue, 19 Jan 2016 23:41:21 -0800   Tue, 19 Jan 2016 23:41:21 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         created            {kubelet 172.17.4.99}       Created with docker id 922bebaa64fa
Tue, 19 Jan 2016 23:41:52 -0800   Tue, 19 Jan 2016 23:41:52 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         created            {kubelet 172.17.4.99}       Created with docker id d6612db94e33
Tue, 19 Jan 2016 23:41:52 -0800   Tue, 19 Jan 2016 23:41:52 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         started            {kubelet 172.17.4.99}       Started with docker id d6612db94e33
Tue, 19 Jan 2016 23:42:22 -0800   Tue, 19 Jan 2016 23:42:22 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         started            {kubelet 172.17.4.99}       Started with docker id 9815d3320ba5
Tue, 19 Jan 2016 23:42:22 -0800   Tue, 19 Jan 2016 23:42:22 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         created            {kubelet 172.17.4.99}       Created with docker id 9815d3320ba5
Tue, 19 Jan 2016 23:42:52 -0800   Tue, 19 Jan 2016 23:42:52 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         created            {kubelet 172.17.4.99}       Created with docker id 922baffcd389
Tue, 19 Jan 2016 23:42:52 -0800   Tue, 19 Jan 2016 23:42:52 -0800   1         deis-workflow-ojpi2         Pod                     spec.containers{deis-workflow}         started            {kubelet 172.17.4.99}       Started with docker id 922baffcd389
Tue, 19 Jan 2016 23:43:09 -0800   Tue, 19 Jan 2016 23:43:09 -0800   1         deis-database-3rwhk         Pod                     spec.containers{deis-database}         created            {kubelet 172.17.4.99}       Created with docker id 004f951dbb67
Tue, 19 Jan 2016 23:43:09 -0800   Tue, 19 Jan 2016 23:43:09 -0800   1         deis-database-3rwhk         Pod                     spec.containers{deis-database}         started            {kubelet 172.17.4.99}       Started with docker id 004f951dbb67
Tue, 19 Jan 2016 23:43:09 -0800   Tue, 19 Jan 2016 23:43:09 -0800   1         deis-database-3rwhk         Pod                     spec.containers{deis-database}         pulled             {kubelet 172.17.4.99}       Successfully pulled image "quay.io/deis/postgres:2.0.0-alpha"
Tue, 19 Jan 2016 23:35:49 -0800   Tue, 19 Jan 2016 23:50:42 -0800   55        deis-router-3pgpt           Pod                                                            failedScheduling   {scheduler }                Failed for reason PodFitsPorts and possibly others
~/code/deis$ kubectl get pods --namespace=deis
NAME                        READY     STATUS    RESTARTS   AGE
deis-builder-vc0xg          1/1       Running   0          19m
deis-database-3rwhk         1/1       Running   0          19m
deis-etcd-1-33zlc           1/1       Running   2          19m
deis-etcd-1-7asrh           1/1       Running   2          19m
deis-etcd-1-a8d98           1/1       Running   2          19m
deis-etcd-discovery-unf2g   1/1       Running   0          19m
deis-minio-35irj            1/1       Running   0          19m
deis-registry-x40ur         1/1       Running   0          19m
deis-router-3pgpt           0/1       Pending   0          19m
deis-workflow-ojpi2         1/1       Running   2          19m
```

**Comment by olalonde** [comment] 2016-01-20 08:17
Just did a vagrant destroy and tried again with a more version of kubernetes and getting same problem.

```bash
39s         39s        1         deis-database-pqlid         Pod                     spec.containers{deis-database}         pulled             {kubelet 172.17.4.99}       Successfully pulled image "quay.io/deis/postgres:2.0.0-alpha"
38s         38s        1         deis-database-pqlid         Pod                     spec.containers{deis-database}         started            {kubelet 172.17.4.99}       Started with docker id fc4a4d83d903
~/code/coreos-kubernetes/single-node$ kubectl version                                                                                                                                             master
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.2", GitCommit:"3085895b8a70a3d985e9320a098e74f545546171", GitTreeState:"clean"}
```

**Comment by krancour** [comment] 2016-01-20 17:58
You would have to describe the router pod to get at the root cause.  Could you try this and post the results?

```
$ kubectl describe pod deis-router-3pgpt --namespace=deis
```

My gut feeling is there is a port conflict.  Router binds to the host's ports 80 and 443.  Something else in this single node cluster may already be tying up one or both of those.  This is just a guess.

**Comment by olalonde** [comment] 2016-01-20 18:28
The [coreos-kubernetes](https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant-single.html) asked me to do this:

```
kubectl config set-cluster vagrant --server=https://172.17.4.99:443 --certificate-authority=${PWD}/ssl/ca.pem
kubectl config set-credentials vagrant-admin --certificate-authority=${PWD}/ssl/ca.pem --client-key=${PWD}/ssl/admin-key.pem --client-certificate=${PWD}/ssl/admin.pem
kubectl config set-context vagrant --cluster=vagrant --user=vagrant-admin
kubectl config use-context vagrant
```

I suppose means the kubernetes API binds to port 443 already?

**Comment by olalonde** [comment] 2016-01-20 18:36
```bash
$ kubectl describe pod deis-router-yenek --namespace=deis                                                          master
Name:                           deis-router-yenek
Namespace:                      deis
Image(s):                       quay.io/deis/router:2.0.0-alpha
Node:                           /
Labels:                         app=deis-router
Status:                         Pending
Reason:
Message:
IP:
Replication Controllers:        deis-router (1/1 replicas created)
Containers:
  deis-router:
    Container ID:
    Image:              quay.io/deis/router:2.0.0-alpha
    Image ID:
    State:              Waiting
    Ready:              False
    Restart Count:      0
    Environment Variables:
      POD_NAMESPACE:    deis (v1:metadata.namespace)
Volumes:
  deis-token-ur0b5:
    Type:       Secret (a secret that should populate this volume)
    SecretName: deis-token-ur0b5
Events:
  FirstSeen     LastSeen        Count   From            SubobjectPath   Reason                  Message
  ─────────     ────────        ─────   ────            ─────────────   ──────                  ───────
  6m            55s             21      {scheduler }                    FailedScheduling        Failed for reason PodFitsHostPorts and possibly others

```

**Comment by bacongobbler** [comment] 2016-01-20 19:41
Most of our dev setups have been a 2-node cluster where the master and minion are considered separate nodes. coreos-kubernetes looks like the master and the minion both sit on one node, so that would explain the PodFitsPorts failures as the kubernetes API is binding to port 443.

**Comment by krancour** [comment] 2016-01-21 05:50
Yep.  This is definitely a port conflict.  I do routinely run Deis on a single node k8s cluster using krancour/micro-kube and I know others have had success using kube-solo.  Both of those don't bind the API to host port 443.  @bacongobbler's advice stands.  I am thinking about how I could perhaps avoid having the router bind to the host ports 80 and 443 and I'm coming up empty-handed.  If I don't, it makes setup on platforms like Vagrant or bare metal a bit more complicated than I'd like.  But I will keep thinking on this, because what you're running into is certain to pop up again.

**Comment by olalonde** [comment] 2016-01-21 18:39
@bacongobbler @krancour thanks for the clarification. I finally managed to get Deis v2 running using both https://github.com/rimusz/coreos-osx-kubernetes-cluster (multi node) and https://github.com/TheNewNormal/kube-solo-osx (single node).

**Comment by bacongobbler** [comment] 2016-01-21 19:15
Awesome! Since we laid out the main issue here and since there's no true workaround for it (other than separating the master and minion on separate nodes) I'm going to go ahead and close this, but please feel free to add more input if you find a solution on running the kubernetes master API server on a different port. Thanks!

**Closed by bacongobbler** 2016-01-21 19:15 UTC
