### ISSUE TITLE
With many (custom) domains the router might be too slow to startup

### ISSUE THREAD

**Issue by nathansamson** [deis/router#212] opened 2016-07-02 20:25 UTC
Scenario:
Have a few applications; but many custom domains. (100s of them, I have around 300, the specific amount that triggers the problem will be dependant on the load and CPU/memory size of the node)

Restart the router replica (eg during an upgrade). One way to achieve this is to run
`kubectl --namespace deis scale rc --replicas=0; kubectl --namespace deis scale rc --replicas=1`

Follow the pods status; see it never coming up; after 20s it will go into Restarts 1
After some more time it restarts again and so on.

It seems the initial configuration is taking so long to build that nginx never comes up, and the K8s system decides to restart it. 

manually removing some domans from the annotations of an application made the routers start again

I worked around this issue by changing the router-rc manifest

~~~
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 60
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 60
          timeoutSeconds: 1
~~~

Note I can not figure out why it initially restarted after 20s, because the initialDelaySeconds was also 1.

Note that I am not sure what the correct solution would be; a few solutions spring to mind

* Make it faster to generate the config. Obviously this only increases the problem treshold, so unless it is like 10 times faster (which is unlikely this is possible) this would not help much
* Make the default config a working config; obviously this has the disadvantage the router is in an up state while in fact it isn't....
* Increase the healthcheck timeout, but again this only changes the treshold a bit...

**Comment by krancour** [comment] 2016-07-03 04:11
I think this is to be expected... that if you saddle the router with a masive amount of configuration, the time to build the model will be larger than the timeout on the liveness checks. If you have hundreds of domains, I think tweaking the health checks at the time of installation is a reasonable thing to do. That said, I'll take a look Tuesday to see if there are any other optimizations that can be made to the checks to make them more tolerant of this scenario.

**Comment by nathansamson** [comment] 2016-07-05 22:38
Note that one of the problems I had investigating the issue was that the logs of the router looked something like this:

~~~
nginx starting...
nginx started
~~~

immediatelly after startup, then after a while the pods stopped working without the pod displaying any logs.
This confused me because it looked like nginx was actually running, and nothing was crashing in the pod, so there was no reason for it to be restarted....


I would suggest to change the logging to something like


~~~
initial nginx starting...
initial nginx started
bulding first config file.... (this can take a while, increase liveness timeout if the application restarts before this finishes)
first config file built
reloading nginx
~~~

or something like that.

**Comment by tmc** [comment] 2016-09-16 00:03
Data point: I ran into this at ~150 domains.

**Comment by helgi** [comment] 2016-09-16 00:07
DNS resolver being slow? https://stackoverflow.com/questions/35949182/nginx-starts-and-stops-too-slowly-15-seconds-delay

**Comment by krancour** [comment] 2016-09-16 00:13
It could also just be the time required to build larger models. In either case, we know that fiddling with the probes is what's called for to compensate if/when this is a concern for a large cluster. Can we close this?

**Comment by tmc** [comment] 2016-09-16 00:23
why not print a hint about this instead of letting the pods just exit? it'd be a much better experience to hint at what's going on, even better to direct to docs.

**Comment by krancour** [comment] 2016-09-16 04:57
The router doesn't know when this happens because the thing that kills it under these circumstances is a k8s probe external to the router itself.

**Comment by tmc** [comment] 2016-09-29 21:53
this happens on as few as 150 domains

**Comment by bacongobbler** [comment] 2016-09-29 22:21
I'll see if I can take a crack at this sometime before the next release.

**Comment by bacongobbler** [comment] 2016-10-06 21:12
I've been trying a multitude of different orientations, all with 250 domains. 1 app with 250 additional domains, 250 apps (each app gets a default domain), 125 apps with one additional domain... All work fine for me. Workflow v2.6.0.

@tmc or @nathansamson can you give me a general setup I can use to reproduce this issue?

**Comment by bacongobbler** [comment] 2016-10-06 21:35
Hold the phone. I retried the test using 125 apps and 1 domain attached to each app and hit this issue. Seems like it has something to do with iterating through each app's configuration. The hunt is on!

**Comment by nathansamson** [comment] 2016-10-06 21:41
Just fyi i my case it were a few apps (2 or 3) with in total a few hundred
domains (approx 300)

So I don't believe the number of apps is the problem but rather the number
of server entries nginx needs to generate.

I guess it is expected you won't hit this every time depending on a lot of
factors like the load on the machine and on k8s server.

**Comment by tmc** [comment] 2016-10-06 22:48
FWIW I have two additional domains on ~50 apps

**Comment by bacongobbler** [comment] 2016-10-07 21:00
From debugging/testing it doesn't seem to get far enough for nginx DNS resolution to come into play, so it's not the DNS resolver. It's just the router trying to build a large nginx.conf, and it's because it loops through each application in serial. I believe our limiting factor now is our call to k8s to [check each app if they have any endpoints in service](https://github.com/deis/router/commit/82aed26c3bb464ce70db49cc1cc506efde19c015). I believe this is good code, it's just one extra API call per app that's causing slowness.

I observed during my testing the router would can handle ~50 apps per second, even with #280. Adding some debug log output, this is what I got with 125 apps and 1 `appname.rocks` domain attached to each app:

```
2016/10/07 20:22:58 building go23...
2016/10/07 20:22:58 building go23.rocks for go23...
2016/10/07 20:22:58 building go24...
2016/10/07 20:22:58 building go24.rocks for go24...
2016/10/07 20:22:58 building go25...
2016/10/07 20:22:58 building go25.rocks for go25...
2016/10/07 20:22:58 building go26...
2016/10/07 20:22:58 building go26.rocks for go26...
2016/10/07 20:22:59 building go27...
2016/10/07 20:22:59 building go27.rocks for go27...
2016/10/07 20:22:59 building go28...
2016/10/07 20:22:59 building go28.rocks for go28...
2016/10/07 20:22:59 building go29...
2016/10/07 20:22:59 building go29.rocks for go29...
2016/10/07 20:22:59 building go3...
2016/10/07 20:22:59 building go3.rocks for go3...
2016/10/07 20:22:59 building go30...
2016/10/07 20:22:59 building go30.rocks for go30...
```

Hopefully deis/charts#368 and #280 can alleviate most of this issue, but I'll continue digging/

**Comment by bacongobbler** [comment] 2016-10-07 21:15
My assumptions were correct. The following patch makes it such that the router config can be loaded in under 1 second:

```
><> git show
commit 166273aa46455d0d87038b5fa7220d6060584def
Author: Matthew Fisher <mfisher@deis.com>
Date:   Fri Oct 7 14:01:16 2016 -0700

    debug: hardcode app is available

diff --git a/model/model.go b/model/model.go
index ede8feb..7dc7e3f 100644
--- a/model/model.go
+++ b/model/model.go
@@ -388,12 +388,7 @@ func buildAppConfig(kubeClient *kubernetes.Clientset, service v1.Service, router
                }
        }
        appConfig.ServiceIP = service.Spec.ClusterIP
-       endpointsClient := kubeClient.Endpoints(service.Namespace)
-       endpoints, err := endpointsClient.Get(service.Name)
-       if err != nil {
-               return nil, err
-       }
-       appConfig.Available = len(endpoints.Subsets) > 0 && len(endpoints.Subsets[0].Addresses) > 0
+       appConfig.Available = true
        return appConfig, nil
 }
```

**Comment by helgi** [comment] 2016-10-07 22:01
@bacongobbler thoughts on finally splitting each app and/or domain into their own files and doing the API fetching in parallel?

The API may throttle the router at one point or another but it could be done in batches and if each app/domain are a config file then you do not end up with file system thrashing or things stepping on one another toes.

**Comment by bacongobbler** [comment] 2016-10-08 03:54
That is be a great idea, though I believe `include`s are required before the main config, which brings us back to requiring all the apps before the first build. I'll check the nginx docs and play around with that a bit, though :)

**Comment by helgi** [comment] 2016-10-08 18:14
@bacongobbler you should be able to do include at the end after the main config by using a `include sites_enabled/*.conf` or similar - Or am I misunderstanding? You mean drop the main config so nginx can be started, then drop all the app configs + `nginx reload`?

In chef nginx things I've done in the past I did it that way, even went as far as doing `include <app_path>/nginx[\\.]conf` to support (optionally, the regex allows for that) app specific overwrites so I think there is enough flexibility. I'm curious if you run into any limitations :)

**Closed** 2016-10-10 17:07 UTC
Labels: in progress, refactor
