### ISSUE TITLE
Router starts but throws errors on some k8s installations

### ISSUE THREAD

**Issue by jchauncey** [deis/router#65] opened 2015-12-21 18:25 UTC
```console
2015/12/21 18:21:08 Error building model; not modifying configuration: Get https://10.100.0.1:443/api/v1/namespaces/deis/replicationcontrollers/deis-router: read tcp 10.244.97.6:56526->10.100.0.1:443: read: connection reset by peer.
2015/12/21 18:21:18 Error building model; not modifying configuration: Get https://10.100.0.1:443/api/v1/namespaces/deis/replicationcontrollers/deis-router: EOF.
```

It also has a blank config

```console
bash-4.3# cat /opt/nginx/conf/nginx.conf
user nginx;
daemon off;
events {}
http {}
```

**Comment by jchauncey** [comment] 2015-12-21 19:02
trying to curl that endpoint gives the following:

```console
bash-4.3# curl -vvv https://10.100.0.1:443/api/v1/namespaces/deis/replicationcontrollers/deis-router
*   Trying 10.100.0.1...
* Connected to 10.100.0.1 (10.100.0.1) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2, TLS Unknown, Unknown (22):
* TLSv1.2, TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to 10.100.0.1:443
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to 10.100.0.1:443
```

**Comment by krancour** [comment] 2015-12-21 19:25
@jchauncey this is a problem authenticating to the k8s API.

Can you show me what the output from this is?

```
$ kubectl exec -it <deis router pod> --namespace=deis -- cat /var/run/secrets/kubernetes.io/serviceaccount/token
```

**Comment by jchauncey** [comment] 2015-12-21 19:40
```console
bash-4.3# cat /var/run/secrets/kubernetes.io/serviceaccount/token
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWlzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlaXMtdG9rZW4tbHZ2dHAiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVpcyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjA2YmI4ZTIwLWE4MGUtMTFlNS1hNDUwLTA4MDAyNzY4NDU2NyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWlzOmRlaXMifQ.Eg_MreyVNpeOMVhBRimk6Y8lfnE-2XCR_2-c7wOMjgKqhm2A3W-XVfqlRqJo7FTEjzZ1xu_d3PIJ2fBuqR5fqUtTQxIlo32jU2BTLAS4_OjDBXWVbCPs1D0gjOqZphfikpxFpJ3oWXnhO1YFcMXeexYN2A94QaZevHVqdktFrLe5y-ytfOnItB9xDeXBbBFhfnmfHPUU74_VvEkWMWjXxHceXGZkPGi5kRKWXvLBVdV0Wat0NQD5wDMxj43gRb0YWT9x1ox4N_fMdRA9z8TuJeaEgc82Q_ss_LBMwlXqkDK7fm-uAo6TdTbZxuGOFD1Nj4M0xg7qYolh7-SYyq9z3w
```

**Comment by rimusz** [comment] 2015-12-27 10:58
I'm seeing the same issues

**Comment by krancour** [comment] 2015-12-28 17:51
This is a dupe of #62.  Closing this so that we keep the discussion all in one place.

**Closed by krancour** 2015-12-28 17:51 UTC
